import { Unbounded, Unbounded, Sora } from "next/font/google";
import "./globals.css";

//FONT AWSOME CSS
import "@fortawesome/fontawesome-svg-core/style.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: [400, 500, 600, 700]
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: [400, 500, 600, 700]
});

export const metadata = {
  title: "Travel Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${sora.variable} ${unbounded.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
